from snakemake.utils import min_version

min_version("7.25.0")


include: "rules/common.smk"
include: "rules/assemblies.smk"
include: "rules/panaroo.smk"


rule all:
    input:
        **get_outputs(),
