max_threads: 8

prokka:
  centre: "CUSP" # Centre name to annotate in prokka outputs, default: CUSP
  mincontiglen: 200 # Minimum contig size [NCBI needs 200], default: 200

panaroo:
  mash_db: "/data/genome/others/mash_db/2024-02-21" # Path to the mash database. Must be timestamped. Will be downloaded if does not exist.
  mode: "sensitive" # The stringency mode at which to run panaroo. Allowed: {strict,moderate,sensitive}
  core_threshold: 0.98 # Core-genome sample threshold
  aligner: "mafft" # Aligner to use in panaroo. Allowed: {prank,clustal,mafft}

threads:
  prokka: 4
  panaroo: 8
  snp_dists: 4
  iqtree: 8
