validate_taxa_and_mlst: True # Fail analysis if GTDBtk taxa and MLST type are not homogeneous among input samples

prokka:
  centre: "CUSP" # Centre name to annotate in prokka outputs, default: CUSP
  mincontiglen: 200 # Minimum contig size [NCBI needs 200], default: 200

panaroo:
  mash_db: "mash_db/2024-02-21"
  mode: "sensitive"
  core_threshold: 0.05
  aligner: "mafft" # Aligner to use in panaroo. Allowed: {prank,clustal,mafft}
  newick_tree: false # Generate a newick tree from the panaroo output, default: true

iqtree:
  bootstrap: null # Number of bootstrap replicates, default: 1000. Minimum: 1000. Set to null or 0 to disable bootstrapping.

max_threads: 2
max_mem_mb: 6000

threads:
  prokka: 2
  panaroo_QC: 2
  panaroo: 2
  snp_dists: 2
  iqtree: 2

resources:
  panaroo_qc__mem__mb: 64000
  panaroo__mem_mb: 16000
