"$schema": http://json-schema.org/draft-06/schema#
"$ref": "#/definitions/OutbreakDetection"
definitions:
  OutbreakDetection:
    type: object
    additionalProperties: false
    properties:
      pepfile:
        type: string
        description: "Path to the PEP file containing the info how to load the data."
        default: "config/pep/config.yaml"
      max_threads:
        type: integer
        description: "Number of maximum threads to use in jobs."
        default: 1
        Minimum: 1
      threads:
        type: object
        "$ref": "#/definitions/Threads"
      panaroo:
        type: object
        "$ref": "#/definitions/Panaroo"
    required:
      - threads
      - panaroo
    title: OutbreakDetection
  Panaroo:
    type: object
    additionalProperties: false
    properties:
      core_threshold:
        type: number
        description: "Core threshold for panaroo."
        default: 0.98
      mash_db:
        type: string
        description: "Path to the mash database."
        pattern: '.*/\d{4}-\d{2}-\d{2}.*'
        default: ""
      mode:
        type: string
        description: "Mode to use for panaroo."
        default: "sensitive"
    required:
      - core_threshold
      - mash_db
      - mode
    title: Panaroo
  Threads:
    additionalProperties: true
    properties:
      prokka:
        type: integer
        default: 1
        description: "Number of threads to use for prokka."
      iqtree:
        type: integer
        default: 1
        description: "Number of threads to use for iqtree"
      panaroo:
        type: integer
        default: 1
        description: "Number of threads to use for panaroo."
      snp_dists:
        type: integer
        default: 1
        description: "Number of threads to use for snp_dists."
    title: Threads
    required:
      - prokka
      - iqtree
      - panaroo
      - snp_dists
