"$schema": http://json-schema.org/draft-06/schema#
"$ref": "#/definitions/OutbreakDetection"
definitions:
  OutbreakDetection:
    type: object
    additionalProperties: false
    properties:
      pepfile:
        type: string
        description: "Path to the PEP file containing the info how to load the data."
        default: "config/pep/config.yaml"
      max_threads:
        type: integer
        description: "Number of maximum threads to use in jobs."
        default: 1
        Minimum: 1
      max_mem_mb:
        type: integer
        description: "Maximum memory in MB to use in jobs."
        default: 2048
        Minimum: 2048
      validate_taxa_and_mlst:
        type: boolean
        default: true
        description: "Fail analysis if GTDBtk taxa and MLST type are not homogeneous among input samples."
      prokka:
        type: object
        "$ref": "#/definitions/Prokka"
      threads:
        type: object
        "$ref": "#/definitions/Threads"
      resources:
        type: object
        "$ref": "#/definitions/Resources"
      panaroo_qc:
        type: object
        "$ref": "#/definitions/PanarooQC"
      panaroo:
        type: object
        "$ref": "#/definitions/Panaroo"
      iqtree:
        type: object
        "$ref": "#/definitions/Iqtree"
    required:
      - threads
      - panaroo
      - iqtree
    title: OutbreakDetection
  Iqtree:
    type: object
    additionalProperties: false
    properties:
      bootstrap_replicates:
        type: [integer, "null"]
        description: "Number of bootstrap replicates, default: 1000. Minimum: 1000"
        default: 1000
      method:
        type: string
        enum:
          - "UFBoot"
          - "standard"
        description: "Method to use for bootstrapping, default: UFBoot"
        default: "UFBoot"
      single_branch_tests:
        type: [string, "null"]
        enum:
          - "SH-aLRT"
          - "abayes"
          - "lbp"
          - "null"
          - null
        description: "Single branch test method to use for assessing branch support."
        default: "SH-aLRT"
    required:
      - bootstrap_replicates
      - method
      - single_branch_tests
  Prokka:
    type: object
    additionalProperties: false
    properties:
      centre:
        type: string
        description: "Centre to use for prokka (default: CUSP)."
        default: "CUSP"
      mincontiglen:
        type: integer
        description: "Minimum contig size [NCBI needs 200], default: 200"
        default: 200
  PanarooQC:
    type: object
    additionalProperties: false
    properties:
      do:
        type: boolean
        description: "Generate a QC report for panaroo."
        default: true
      mash_db:
        type: string
        description: "Path to the mash database."
        pattern: '.*/\d{4}-\d{2}-\d{2}.*'
        default: ""
    required:
      - do
      - mash_db
  Panaroo:
    type: object
    additionalProperties: false
    properties:
      core_threshold:
        type: number
        description: "Core threshold for panaroo."
        default: 0.98
      mode:
        type: string
        description: "Mode to use for panaroo."
        default: "sensitive"
        enum:
          - "strict"
          - "moderate"
          - "sensitive"
      aligner:
        type: string
        description: "Aligner to use for panaroo."
        default: "mafft"
        enum:
          - "prank"
          - "clustal"
          - "mafft"
      newick_tree:
        type: boolean
        description: "Generate a newick tree from the panaroo output."
        default: true
    required:
      - core_threshold
      - aligner
      - mode
      - newick_tree
    title: Panaroo
  Resources:
    additionalProperties: true
    panaroo_qc__mem__mb:
      type: integer
      description: "Memory in MB to reserve for panaroo QC."
      default: 2048
    panaroo__mem_mb:
      type: integer
      description: "Memory in MB to reserve for panaroo."
      default: 2048
    required:
      - panaroo_qc__mem__mb
      - panaroo__mem_mb
    title: Resources
  Threads:
    additionalProperties: true
    properties:
      prokka:
        type: integer
        default: 1
        description: "Number of threads to use for prokka."
      iqtree:
        type: integer
        default: 1
        description: "Number of threads to use for iqtree"
      panaroo:
        type: integer
        default: 1
        description: "Number of threads to use for panaroo."
      snp_dists:
        type: integer
        default: 1
        description: "Number of threads to use for snp_dists."
    title: Threads
    required:
      - prokka
      - iqtree
      - panaroo
      - snp_dists
