name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Formatting
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true

  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint workflow
        uses: xsitarcik/snakemake-github-action@v1.25.1
        with:
          directory: .tests
          snakefile: workflow/Snakefile
          stagein: mamba install -n snakemake -c conda-forge peppy
          args: "--lint"

  Testing:
    runs-on: ubuntu-latest
    needs:
      - Linting
      - Formatting
    steps:
      - uses: actions/checkout@v4

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: false
          swap-storage: true

      - name: Test workflow
        uses: xsitarcik/snakemake-github-action@v1.25.1
        with:
          directory: .tests
          snakefile: workflow/Snakefile
          stagein: "conda config --set channel_priority flexible"
          args: "--use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache"
          show-disk-usage-on-error: true

      # - name: Test report
      #   uses: xsitarcik/snakemake-github-action@v1.25.1
      #   with:
      #     directory: .tests
      #     snakefile: workflow/Snakefile
      #     args: "--report report.zip"
      #     show-disk-usage-on-error: true
